services:
  influxdb:
    build: 
      context: ./influxdb
      args:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234 
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=network-data 
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_TOKEN
    container_name: fyp-influxdb
    ports:
      - "8086:8086"

  telegraf: 
    build: 
      context: ./telegraf
      args:
        - INFLUXDB_TOKEN=$INFLUXDB_TOKEN
    container_name: fyp-telegraf
    ports:
      - "57500:57500"
      - "8080:8080"
    # depends_on:
    #   - influxdb

  # grafana:
  #   build: 
  #     context: ./grafana
  #     args:
  #       - INFLUXDB_TOKEN=$INFLUXDB_TOKEN
  #   container_name: fyp-grafana
  #   ports:
  #     - "3000:3000"

  # ollama:
  #   image: X
  #   container_name: fyp-ollama
  #   restart: unless-stopped
  #   ports:
  #     - '11434:11434'