services:
  influxdb:
    image: fyp-influxdb:latest
    container_name: fyp-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/configuration/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234 
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=network-data 
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_TOKEN

  telegraf:
    image: fyp-telegraf:latest
    container_name: fyp-telegraf
    restart: unless-stopped
    environment:
      - INFLUXDB_TOKEN=$INFLUXDB_TOKEN
    ports:
        - "57500:57500"
        - "8080:8080"
    volumes:
      - ./telegraf/configuration/:/etc/telegraf/
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: fyp-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/default.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards/dashboard_dummy.json:/etc/grafana/provisioning/dashboards/dashboard_dummy.json
      - ./grafana/dashboards/dashboard_network.json:/etc/grafana/provisioning/dashboards/dashboard_network.json
    depends_on:
      - influxdb

# from(bucket: "network_data")
#   |> range(start: -1d)