services:
  data_collector:
    build: 
      context: ./data_collecter
      args:
        - INFLUXDB_TOKEN=$INFLUXDB_TOKEN
    container_name: fyp_data_data_collecter

  influxdb:
    build: 
      context: ./influxdb
      args:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234 
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=network-data 
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_TOKEN
    container_name: fyp-influxdb
    ports:
      - "8086:8086"

  grafana:
    build: 
      context: ./grafana
      args:
        - INFLUXDB_TOKEN=$INFLUXDB_TOKEN
    container_name: fyp-grafana
    ports:
      - "3000:3000"

  alert_api:
    build: 
      context: ./alert_api
    container_name: fyp-alert_api
    ports:
      - "49000:49000"