FROM grafana/grafana

WORKDIR /

USER root

COPY configuration/ /tmp/configuration/

RUN mv /tmp/configuration/grafana.ini /etc/grafana/grafana.ini \
    && mv /tmp/configuration/datasources.yml /etc/grafana/provisioning/datasources/default.yml \
    && mv /tmp/configuration/dashboard.yml /etc/grafana/provisioning/dashboards/dashboard.yml \
    && mv /tmp/configuration/dashboards/ /etc/grafana/provisioning/dashboards/ \
    && rm -rf /tmp/configuration/

EXPOSE 3000

ARG INFLUXDB_TOKEN
ENV INFLUXDB_TOKEN=${INFLUXDB_TOKEN}