apiVersion: 1
groups:
    - orgId: 1
      name: 10 Seconds
      folder: Services
      interval: 10s
      rules:
        - uid: eefiuotzp6dq8e
          title: 'BGP State '
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: P951FEA4DE68E13C5
              model:
                datasource:
                    type: influxdb
                    uid: P951FEA4DE68E13C5
                instant: false
                intervalMs: 1000
                maxDataPoints: 43200
                query: |-
                    from(bucket: "network-data")
                      |> range(start: -6h)
                      |> filter(fn: (r) => r._measurement == "bgp_status")
                      |> filter(fn: (r) => r.device_name == "router-1")
                      |> filter(fn: (r) => r._field == "bgp_state")
                      |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
                      |> map(fn: (r) => ({ r with bgp_state: if r.bgp_state == "established" then 1 else 0 }))
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.9
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                      unloadEvaluator:
                        params:
                            - 0.9
                            - 0
                        type: gt
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: eee9jajpxup6ob
          panelId: 3
          noDataState: OK
          execErrState: OK
          annotations:
            __dashboardUid__: eee9jajpxup6ob
            __panelId__: "3"
            description: There is an issue with BGP for router-1 and its neighbour.
            summary: BGP Issue
          labels: {}
          isPaused: false
          notification_settings:
            receiver: alert
        - uid: befj04oth58n4b
          title: OSPF State
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: P951FEA4DE68E13C5
              model:
                datasource:
                    type: influxdb
                    uid: P951FEA4DE68E13C5
                instant: false
                intervalMs: 1000
                maxDataPoints: 43200
                query: |-
                    from(bucket: "network-data")
                      |> range(start: -6h)
                      |> filter(fn: (r) => r._measurement == "ospf_status")
                      |> filter(fn: (r) => r.device_name == "router-1")
                      |> filter(fn: (r) => r._field == "ospf_state")
                      |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
                      |> map(fn: (r) => ({ r with ospf_state: if r.ospf_state == "ospf-nbr-full" then 1 else 0 }))
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                settings:
                    mode: ""
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                      unloadEvaluator:
                        params:
                            - 1
                            - 0
                        type: gt
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: eee9jajpxup6ob3
          panelId: 4
          noDataState: OK
          execErrState: OK
          annotations:
            __dashboardUid__: eee9jajpxup6ob3
            __panelId__: "4"
            description: There is an issue with OSPF for router-1 and its neighbour
            summary: OSPF Neighbour Down
          labels: {}
          isPaused: false
          notification_settings:
            receiver: alert
