apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://fyp-influxdb:8086
    jsonData:
      version: Flux
      organization: "my-org"
      defaultBucket: "network-data"
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}