{
 "title": "Router 1 - OSPF",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "OSPF State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"network-data\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"ospf_status\")\n  |> filter(fn: (r) => r.device_name == \"router-1\")\n  |> filter(fn: (r) => r._field == \"ospf_state\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with ospf_state: if r.ospf_state == \"ospf-nbr-full\" then 1 else 0 }))"
    }
   ]
  },
  {
   "title": "Interface Issues",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"network-data\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"interfaces\")\n  |> filter(fn: (r) => r.router == \"router-1\")\n  |> filter(fn: (r) => r._field == \"errors\" or r._field == \"duplex\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"network-data\")\n  |> range(start: -48h)\n  |> filter(fn: (r) => r._measurement == \"interface_status\")\n  |> filter(fn: (r) => r.device_name == \"router-1\")\n  |> filter(fn: (r) => r._field == \"oper_status\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with oper_status: if r.oper_status == \"up\" then 1 else 0 }))"
    }
   ]
  }
 ]
}