FROM python:3.11-alpine

WORKDIR /app

COPY /code/ /app/

RUN pip install --no-cache-dir -r requirements.txt

ARG INFLUXDB_TOKEN
ENV INFLUXDB_TOKEN=${INFLUXDB_TOKEN}

ENTRYPOINT ["python", "ncclient_telegraf.py", "--env", "container", "--url" ,"fyp-influxdb" , "--device", "device/router-1.json"]