FROM telegraf:latest as base

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=true \
    PIP_ROOT_USER_ACTION=ignore \
    PIP_NO_WARN_SCRIPT_LOCATION=0 \
    PIP_DISABLE_ROOT_WARNING=ignore

RUN apt update \
    && apt install -y python3  python3-venv  sudo \
    && python3 -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY configuration/requirements.txt /tmp/requirements.txt

RUN python3 -m pip install --upgrade pip \
    && pip install -r /tmp/requirements.txt \
    && rm /tmp/requirements.txt \
    && echo 'alias ll="ls -al"' >> ~/.bashrc

FROM base as telegraf

EXPOSE 57500
EXPOSE 8080

ARG INFLUXDB_TOKEN
ENV INFLUXDB_TOKEN=${INFLUXDB_TOKEN}

COPY configuration/ /tmp/configuration/
RUN mv /tmp/configuration/telegraf.conf /etc/telegraf/telegraf.conf \
    # && mv /tmp/configuration/stream_telem.conf /etc/telegraf/telegraf.d/stream_telem.conf \
    # && mv /tmp/configuration/netconf.conf /etc/telegraf/telegraf.d/netconf.conf \
    && mv /tmp/configuration/device /etc/telegraf/ \
    && mv /tmp/configuration/ncclient_telegraf.py /etc/telegraf/ \
    && rm -rf /tmp/configuration